fieldLayouts:
  f0e352ef-6b9d-4c19-a8dc-c21691f16576:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d40e6b4-5db5-4369-aa3d-3ccc61ac7a91
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ea70667-2e04-4b0b-8104-efc2a6d6eccf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5defbf32-4311-4819-8d92-c6743781b480
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5663e54-a314-4fd1-b8b5-a482fdef6631
            userCondition: null
            warning: null
            width: 100
        name: Navigatie
        uid: 19b44313-aa5e-4e67-a633-c67b38aa1735
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 5
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
