fieldLayouts:
  9a5a3f88-2d2f-4a94-b539-6958abde5a7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e024900c-3e18-4fa6-9ad0-ef2e8019acdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Header
            type: craft\fieldlayoutelements\Heading
            uid: b6dc312e-89e0-457f-91aa-a2fdf802060c
            userCondition: null
          -
            elementCondition: null
            fieldUid: 8fa4ab2b-d31b-4bd6-b6d8-ee2df12c14e5 # Afbeelding 1
            instructions: null
            label: 'Afbeelding header'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf813f17-10a4-4bd8-a0ce-c364ae72fb86
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Shop preview'
            type: craft\fieldlayoutelements\Heading
            uid: 4f696775-f4fd-4675-99f9-7fadb7b0d5e2
            userCondition: null
          -
            elementCondition: null
            fieldUid: 31bb0e04-2a70-4557-8090-a52c1a2254f2 # Titel 1
            instructions: null
            label: 'Shop titel'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b02feba5-fc43-4ff8-af51-2bdf740f2118
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6fe480a1-4d15-498b-90c0-51adb5580098 # Uitgelichte producten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be1cd2e6-5448-4fb4-9101-c089a07c60b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Work Sectie'
            type: craft\fieldlayoutelements\Heading
            uid: 2bc64802-9f31-4a11-84db-cf7cab644ba5
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2d03ce61-2ba5-467f-ab56-c487d039e6ec # Titel 2
            instructions: null
            label: Titel
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f915dcc-6d22-4ba0-9f57-96ebb4be5680
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d1f9737c-c74a-4ffd-8fde-fed08a33c48c # Afbeelding 2
            instructions: null
            label: Afbeelding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db433cc0-d285-48dd-85f0-97cdf5976c6f
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 00c5f631-3ba6-4457-8520-81aaf01dbc68 # Beschrijving 1
            instructions: null
            label: Beschrijving
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb532826-2f21-4c1d-ad38-4b9a0adcc86b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 02f25b1a-2d32-4626-8ab1-ed9e9f3dae3d # Link 1
            instructions: null
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 832e0ec0-1382-448b-b1a7-d137363153dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'About sectie'
            type: craft\fieldlayoutelements\Heading
            uid: 237a72a2-38d4-49a6-b751-fa5b0006e9e4
            userCondition: null
          -
            elementCondition: null
            fieldUid: 38e6a148-3a70-43f5-8128-54ff53c63eb2 # Titel 3
            instructions: null
            label: Titel
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df1ef8ab-f233-41da-a31e-5d3212214403
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f2fda0de-15eb-4ada-a4c1-c88f8dc38392 # Afbeelding 3
            instructions: null
            label: Afbeelding
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abc720d1-bd5e-4b81-93cf-cf65e361d597
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: cddc48cb-cf17-49ea-96d9-773668a2239f # Beschrijving 2
            instructions: null
            label: Beschrijving
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 236791d9-3105-4d5e-bcfa-8a59879ce7ec
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e6d64dd2-c9e9-410c-81b6-82ffa3358eeb # Link 2
            instructions: null
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db80b016-9885-40c5-97b9-7a1fe9e49d2b
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 995c4c91-d868-48bd-be12-16a7b2892d89
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c88515a-8032-4a79-94ce-1a74c8074ddf # Toon in navigatie
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10210e34-0796-4ca6-92ad-bc7d65a34411
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbd11bc6-ad86-4953-959b-f3fb418b6153 # Toon in footer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee75781-1976-4f4b-a53e-1b26eba56eda
            userCondition: null
            warning: null
            width: 100
        name: Navigatie
        uid: cc2ca63e-7c17-4fc8-9ea6-fad1f31d19a2
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a3b7618e-f5d1-4b5f-bd32-db20dd35c26b # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d408d803-0da7-4157-8cd3-29f473006fc5
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3e063cb9-5324-4eaf-981f-f98e76d5e541
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 2c1c4276-6b14-4857-8873-c475c0a68f0a # Pagina's
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
