defaultPlacement: end
enableVersioning: true
handle: contactSubmissions
name: 'Contact berichten'
propagationMethod: all
siteSettings:
  9b464eb3-586e-4db0-bf51-3d00017432b0: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  361382ab-c268-4ec2-a944-660822aea169: # Nederlands
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
